### ISSUE TITLE
configure: Allowing --disable-static-libs instead of --enable-static=no

### ISSUE THREAD

**Issue by mmokrejs** [jkbonfield/io_lib#11]
Hi James,
  would it be possible to change configure to listen to more common `--enable-foo` or `--disable-foo` or `--with-foo` or `--without-foo` arguments? Currently, one is supposed to state:

`--enable-static=[yes|no]`

  I went around with the Gentoo Linux package for 1.14.11 but I thought to at least mention this.

**Comment by jkbonfield** [comment]
It's using a fairly minimal and standard configure setup, so I don't think io_lib is in any way non-standard here.  I didn't add any of the static stuff myself.  This just comes automatically from using libtool and I really don't want to try writing my own custom variant of it.

Do you have specific examples of packages that are doing something different?

**Comment by mmokrejs** [comment]
In the package definition file there are ready-made hooks (through many ebuild classes) to append `--enable-foo` or `--disable-foo` or `--with-foo` or `--without-foo` but to get `--enable-static=no` crafted I needed to invent "my own" code. So, merely because of this I think this is uncommon. Let me add @mgorny and @SoapGentoo tot he discussion.

**Comment by mgorny** [comment]
I don't really understand what this bug is about. I don't see any custom logic for `--enable-static`, and if there isn't one, then I don't see why `--disable-static` wouldn't work (and yes, the standard flag is `--disable-static`, not `--disable-static-libs`).

**Comment by jkbonfield** [comment]
Closing as no movement in the discussion and I don't believe this is a real problem.
