### ISSUE TITLE
Add BAM and fastq size to benchmarks

### ISSUE THREAD

**Issue by kyleabeauchamp** [jkbonfield/io_lib#14]
The size, encoding, and decoding benchmark on README.md is a bit hard to interpret because I it doesn't have a good reference point of the original BAM size.

**Comment by kyleabeauchamp** [comment]
May also want read length

**Comment by jkbonfield** [comment]
Given the main purpose of this table is CRAM v3.1 onwards, I updated in the latest branch involving these.  See https://github.com/jkbonfield/io_lib/tree/CRAM4_updates2

There are more tests I have with other datasets, but I don't want the README file to be an exhaustive analysis.  I may add more later to another file.

Edit: I need to expand BAM to bgzf via zlib (shown here) vs libdeflate.  It's an important point to hammer home as it's well worth the hassle of the extra dependency!

**Comment by kyleabeauchamp** [comment]
Thanks, I just really need to see that 500MB baseline.
