### ISSUE TITLE
LDFLAGS as configure argument

### ISSUE THREAD

**Issue by dkj** [jkbonfield/io_lib#15]
`./configure` isn't using `LDFLAGS` when passed as an argument to the configure script, this is forcing a non-standard workaround when building (passing the LDFLAGS as an argument to `make`) which is a niggle: kjsanger/npg_conda/pull/5

**Comment by dkj** [comment]
Our problem was fixed when I stopped using `--with-libcurl=` and `--with-zlib=` at the same time as a `LDFLAGS=` argument to the `./configure`

kjsanger/npg_conda/pull/6

**Comment by jkbonfield** [comment]
As expected, it was still a bug in the io_lib configure script.  Typo! :-)

Fixed by https://github.com/jkbonfield/io_lib/commit/5a2d91bd575dd3f5b4381bda5712edaa7d6d63fe
