### ISSUE TITLE
strncpy calls

### ISSUE THREAD

**Issue by gt1** [jkbonfield/io_lib#18]
I see a few warnings like

```
In file included from /usr/include/string.h:630, from cram_io.c:60:
In function ‘full_path’, inlined from ‘cram_write_SAM_hdr’ at cram_io.c:4622:3:
cram_io.c:4564:6: warning: ‘__builtin_strncpy’ specified bound 4096 equals destination size [-Wstringop-truncation]
 4564 |      strncpy(out, in, PATH_MAX);
```

when compiling io_lib with gcc 9.1.0. The complaint here is that out is an array of size PATH_MAX, so there is no space for putting an extra 0 in case in actually has PATH_MAX non null symbols. Maybe making sure there is a terminator in all cases would be a good idea (in terms of security).

**Comment by jkbonfield** [comment]
How very picky, given the adjacent line:

```
        strncpy(out, in, PATH_MAX);
        out[PATH_MAX-1] = 0;
```

I guess I need to use PATH_MAX-1 to silence the whine.  I'm building gcc9 so I can explore this first though.

Thanks for the bug report.
