### ISSUE TITLE
current master does not build with current instructions

### ISSUE THREAD

**Issue by maarten-k** [jkbonfield/io_lib#19]
The current instructions do not take into account a separate htscodecs repo. I was able to to build with: 

```
git clone git@github.com:jkbonfield/io_lib.git
cd io_lib
git clone git@github.com:jkbonfield/htscodecs.git
cd htscodecs
autoreconf -i
cd ..
autoreconf -i
./configure 
make
```

**Comment by jkbonfield** [comment]
Thanks for the report.  I'll fix this. 

It's better to either use `git clone -r` or to use `git submodule update --init` to get the htscodecs submodule in place.

As for the `autoreconf`` bits, I provide a bootstrap script that does this for you so again that should be mentioned in the README.

Thanks.
