### ISSUE TITLE
HTScodecs submodule commit does not exist

### ISSUE THREAD

**Issue by fwip** [jkbonfield/io_lib#20]
When cloning from source, the referenced version of htscodecs (d08a84db103c1cc460af8cded0c76987e8ed591d) does not seem to be publicly available.

```
$ git submodule update --init
error: Server does not allow request for unadvertised object d08a84db103c1cc460af8cded0c76987e8ed591d
Fetched in submodule path 'htscodecs', but it did not contain d08a84db103c1cc460af8cded0c76987e8ed591d. Direct fetching of that commit failed.
```

I did `cd htscodecs ; git checkout master ; cd ..` to workaround this issue for now, but I don't know what the "right" version is to use with the current version of io_lib.

Thank you for all your work on this software, and let me know if I can be of any help with regards to this issue.

**Comment by jkbonfield** [comment]
Thanks for the bug report.  I'm not sure how I ended up with that commit hash in there.  I bumped it to the current master which is sufficient.

I do have some other fixes to go in to htscodecs, but it's premature to be pointing io_lib to that version other than within my more experimental branches (eg CRAM4b).

**Comment by fwip** [comment]
Thanks!
