### ISSUE TITLE
scramble works really nice

### ISSUE THREAD

**Issue by sebhtml** [jkbonfield/io_lib#23]
This is just a comment about CRAM and scramble.

> At GA4GH we believe in the idea of collaborating on standards and competing on implementations.
(https://www.ga4gh.org/news/guest-post-seven-myths-about-cram-the-community-standard-for-genomic-data-compression/)

I really agree !

So...

scramble is really impressive ! It is really fast !

My sorted BAM contains the quality "*", and my reference file has 3.3 M references

I looked at the cram_dump output. This stuff is neat.

Here are my file sizes in my tests:

3.3G    SRR1259624.sort.sam
909M    SRR1259624.sort.sam.gz
1.1G    SRR1259624.sort.bam
351M    SRR1259624.cram
423M    SRR1259624.cram.cram_dump
91M     SRR1259624.cram.cram_dump.gz
342M    SRR1259624.cram.gz
905M    SRR1259624.V2.0.cram
348M    SRR1259624.V2.0.cram.gz
905M    SRR1259624.V2.1.cram
348M    SRR1259624.V2.1.cram.gz
352M    SRR1259624.V3.0.cram
343M    SRR1259624.V3.0.cram.gz
342M    SRR1259624.V3.1.cram
333M    SRR1259624.V3.1.cram.gz
336M    SRR1259624.V4.0.cram
333M    SRR1259624.V4.0.cram.gz

**Comment by jkbonfield** [comment]
Thanks.  Closing this as it's a (nice) comment rather than an issue to resolve.

Gzipping CRAM is largerly pointless, at least once we got to version 3 where we permitted compressed SAM headers.  That'll be the bulk of your data given 3.3 million references and a relatively small test file.

Arguably it should permit bzip2 and others on the header block too, but maybe this is best fixed by adding zstd into the mix for CRAM 4.

**Comment by sebhtml** [comment]
I see.

720412 kiB	SRR9300372-0023.cram.gz
723608 kiB	SRR9300372-0023.cram

It is true that the size is mostly the same.

**Comment by sebhtml** [comment]
I tried to generate a CRAM file with only the SAM header lines as input to see how much space is used for only the header. An empty file was generated:

707M	SRR9300372-0023.cram
378M	SRR9300372-0023-header.sam
105M	SRR9300372-0023-header.bam
0	SRR9300372-0023-header.cram

Command:
`scramble -V4.0 -j -I bam -O cram \
    -r ~/Picea_glauca_WS77111/Assemblies/WS77111_V1/WS77111_V1.fasta \
     < SRR9300372-0023-header.bam > SRR9300372-0023-header.cram`

**Comment by jkbonfield** [comment]
Did you get any error messages?  It shouldn't produce a zero length file (it should have an `@PG` line if nothing else) and for me this works just fine.

**Comment by sebhtml** [comment]
I ran the command again and this time it works just fine. Maybe yesterday I closed the terminal or whatnot. Sorry for that..

```
$ du -h SRR9300372-0023.cram SRR9300372-0023-header.sam SRR9300372-0023-header.bam SRR9300372-0023-header.cram
707M	SRR9300372-0023.cram
378M	SRR9300372-0023-header.sam
105M	SRR9300372-0023-header.bam
80M	SRR9300372-0023-header.cram

```

The header contains these lines:

```
$ cat SRR9300372-0023-header.sam | awk '{print $1}' | uniq -c
      1 @HD
3353720 @SQ
      4 @PG

```

So, it is 80 MiB that is exactly the same for all my [numerous CRAM files](https://gist.github.com/sebhtml/6b747cb6621c31b48e8331051f2934b0). Regardless, CRAM V4 with bzip2 reduces the needed space a lot when compared to BAM.
