### ISSUE TITLE
Allow scramble to discard tags

### ISSUE THREAD

**Issue by jhaezebrouck** [jkbonfield/io_lib#24]
Hello,

I was wondering if there could be an option in scramble that would allow to discard tags.
I have seen that this is possible in crumble using the -T option, but I don't think this option for scramble is available atm?

Thanks.

**Comment by jkbonfield** [comment]
Yes that's a good idea.  Note it's already in `cram_filter` too which can be more efficient in some cases, but better to avoid writing them in the first place.  Some tags in particular (QO, BD, BI) are real hogs and largely unnecessary.

Sadly -t is used for threads and -T has an experimental usage (which could be changed, but given -t is taken probably no point).  I'll think of something different.

**Comment by jkbonfield** [comment]
Added using -d / -D.  These (partly) match the `samtools view -d`, although -D has a different meaning there.

They have an extended syntax compared to `cram_filter` and `crumble`, permitting simple wildcards with "[a-z]" and ".", so `-D ..` removes all tags and `-d [A-Z][A-Z0-9]` retains only tags matching the official namespace.

**Comment by jhaezebrouck** [comment]
Thank you very much!

**Comment by jkbonfield** [comment]
Thanks, although I appear to have broken MacOS builds!  I should have done a branch first to test Travis rather than just local compilations.  Anyway I'll sort it. :)
