### ISSUE TITLE
Installation Error in io_lib

### ISSUE THREAD

**Issue by Abby3017** [jkbonfield/io_lib#35]
System - ubuntu 18.04 - Linux 5.4.0-52-generic

Download - io_lib-1.14.13 tar from github 

Steps to build -
1. ./configure
2. make
3. sudo make install

When running command scramble, following error is throwing up -
> scramble: error while loading shared libraries: libstaden-read.so.14: cannot open shared object file: No such file or directory

In my /usr/local/lib folder
> libhtscodecs.a	libhtscodecs.la  libstaden-read.a  libstaden-read.la  libstaden-read.so  libstaden-read.so.14  libstaden-read.so.14.1.0

I also tried using io_lib master branch and running ./bootstrap before running above command. Still same error is throwing up.

**Comment by jkbonfield** [comment]
This is probably a consequence of /usr/local/lib not being in your LD_LIBRARY_PATH or ld.so.cache configuration.

During "make install" it probably said something like this (I was using another location as I don't have root access):

```
----------------------------------------------------------------------
Libraries have been installed in:
   /tmp/iolib-install/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
```

(I'm wondering if `LIBDIR` is meant to be something more concrete?)  However if you manually do `export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH` first does it work?

However for me the scramble executable was built automatically using rpath by libtool, so it had this directory included.  The compile line it used for the library was:

```
/bin/bash ../libtool  --tag=CC   --mode=link gcc  -Wall -g -O3 -version-info 2:0:0   -o libhtscodecs.la -rpath /tmp/iolib-install/lib pack.lo rle.lo fqzcomp_qual.lo rANS_static.lo rANS_static4x16pr.lo tokenise_name3.lo arith_dynamic.lo -lz -lpthread -lbz2
...
libtool: link: gcc -Wall -g -O2 -o .libs/scramble scramble.o  ../io_lib/.libs/libstaden-read.so -lm -lpthread -llzma -lbz2 -pthread -Wl,-rpath -Wl,/tmp/iolib-install/lib
```

Hence tools linked against it automatically obtained /tmp/iolib-install/lib in their search path.  You can validate this via objdump or ldd:

```
$ objdump -x /tmp/iolib-install/bin/scramble|grep iolib-install
/tmp/iolib-install/bin/scramble:     file format elf64-x86-64
/tmp/iolib-install/bin/scramble
  RUNPATH              /tmp/iolib-install/lib

$ ldd /tmp/iolib-install/bin/scramble |grep staden
	libstaden-read.so.14 => /tmp/iolib-install/lib/libstaden-read.so.14 (0x00007f524db7f000)
```

I'm afraid I cannot reproduce your problem.

It's possible if you reconfigured it after building or changed prefix during `make install` that it hasn't got the correct configuration.  In that case "make clean" and start again.

**Comment by jkbonfield** [comment]
Closing as couldn't reproduce as it's a stale issue.
