### ISSUE TITLE
io_lib CRAM encoding interface

### ISSUE THREAD

**Issue by gt1** [jkbonfield/io_lib#39]
Hi James,

I found another small thing:

The CRAM encoding interface in cram_bambam.c only gets compiled when CRAM_IO_CUSTOM_BUFFERING is set, but that is defined inside os.h, which does not get included by cram_bambam.c . I guess the thing to do here would be to add

#include <os.h>

in cram_bambam.c

What do you think?

Best,
German

**Comment by jkbonfield** [comment]
I think that's a trivial fix and shouldn't harm.  Can you confirm it fixes things for you?  If so I'll do it (or you can submit a PR if so inclined and wish to be author of the change).

**Comment by gt1** [comment]
Yes this fixes things for me. Could you commit it please?

**Comment by jkbonfield** [comment]
Thanks.  Fixed.

I don't have any immediate plans for a release as it only affects a somewhat less-frequently used part of the API and it looks like Conda is applying patches anyway which is a fine approach.  If it's causing headaches upstream though I could be persuaded to tag a small bug fix release.

**Comment by matthdsm** [comment]
Hi James, German

Thanks for the fixes.
Could I persuade you to create a bugfix release? I've made the appropriate patches from the main app in the conda recipe, but sadly I can't patch the edits in the htscodecs submodule.

Thanks
Matthias

**Comment by jkbonfield** [comment]
That's a good point.  While the changes to io_lib are very limited in scope, htscodecs has had a lot of fixes including potential security issues.

**Comment by gt1** [comment]
Apologies James, I should have been more precise. The include statement

```
#include "io_lib/os.h"
```

needs to be right below

```
#ifdef HAVE_CONFIG_H
#include "io_lib_config.h"
#endif
```

It has no effect at the place it is currently located at (which is only compiled if CRAM_IO_CUSTOM_BUFFERING is set, which is defined in os.h)

________________________________________
Von: James Bonfield ***@***.***>
Gesendet: Dienstag, 16. März 2021 16:41
An: jkbonfield/io_lib
Cc: German Tischler-Höhle; Author
Betreff: [EXTERNAL]Re: [jkbonfield/io_lib] io_lib CRAM encoding interface (#39)

WARNING: This email was sent from an address outside the company. Do not click on any links or open any file attachments unless you recognize the sender and are confident the content is safe.

Thanks. Fixed.

I don't have any immediate plans for a release as it only affects a somewhat less-frequently used part of the API and it looks like Conda is applying patches anyway which is a fine approach. If it's causing headaches upstream though I could be persuaded to tag a small bug fix release.

**Comment by jkbonfield** [comment]
Oops sorry.  The main problem here is the difficulty in testing it!  I need a better test harness including the biobambam specific bits I guess.  I'll correct it.

Edit: and duh! I really should have spotted it wasn't going to do anything there.  I'm just juggling too much atm and not thinking straight.

**Comment by jkbonfield** [comment]
Can you please confirm if it's all building fine for you now from master and is interracting properly with libmaus2?

If so I can tag a new release.

**Comment by gt1** [comment]
Yes, now it builds fine and the interfaces work.

Thanks

**Comment by jkbonfield** [comment]
Thanks German for your assistance.

**Comment by jkbonfield** [comment]
New release (1.14.14) made.

Thanks for bug reporting and patches all.

**Comment by matthdsm** [comment]
Thank you both for the quick responses!
The new release is already pushed to conda!
https://github.com/bioconda/bioconda-recipes/pull/27432
