### ISSUE TITLE
Any updates on cram v3.1 standard?

### ISSUE THREAD

**Issue by matthdsm** [jkbonfield/io_lib#45]
Hi,

The previous release states that cram v3.1 should become the GA4GH standard later in 2020.
Since we're halfway 2021, are there any updates on that front?

Thanks
M

**Comment by jkbonfield** [comment]
Hello Matthias,

A good question.  Sadly there is nothing concrete to report yet.  It's currently blocked by the GA4GH requirement of a second implementation, which there appears to have been little desire to put effort into despite the obvious benefits over CRAM 3.1.  It's been a rather frustrating time and out of my control.

However more recently there has been discussion on providing resources to do this within htsjdk, so hopefully in time this will resolve itself.  I don't know how long that will take though.

Meanwhile I have been taking the opportunity to explore improvements to the new CRAM 3.1 rANS codec in terms of speed via SIMD usage.  It does however mean a modification to the specification (larger numbers of interleaved rANS streams), but I hope this can be discussed with whoever picks up the mantle at the Broad to do the htsjdk code.  For the curious, see https://github.com/samtools/htscodecs/pull/26

PS.  I realise this multiple-implementation requirement may put GA4GH at a disadvantage compared to some other organisations, but it is definitely useful in most situations.  However it's mainly for full file formats and protocols.  It's arguable given the nature of 3.1 being codec changes only (4.0 would be a different beast) that this isn't something that *needs* to be so strict, although it is still beneficial.  We didn't particularly have that requirement for external codecs such as bzip2 and lzma, although it could be argued they're so well tested externally that that requirement is irrelevant. (And actually now there are multiple implementations, although probably not initially.)  At the very least it needs a second person to go through the updated cram-codecs specification and validate that it makes sense, is appropriate for the task and is complete.  AFAIK that also hasn't yet happened.

**Comment by matthdsm** [comment]
Hi James,
Thanks for the quick reply! If I come across any tools that implement v3.1 I'll let you know!

M
