### ISSUE TITLE
Changing result between runs

### ISSUE THREAD

**Issue by matthdsm** [jkbonfield/io_lib#48]
Hi,

I'm trying to add scramble to nf-core, but it seems the results are inconsistent, yielding a different checksum every time scramble is run.
Is this expected behavior? Is there a way to make this process deterministic?

https://github.com/nf-core/modules/pull/1499

Thanks
Matthias

**Comment by jkbonfield** [comment]
I see your command is:

```
    scramble \
        -I bam \
        -O cram \
        -r ${fasta} \
        -t $task.cpus \
        ${bam} \
        ${prefix}.cram
 ```
 
Are those variable expansions always identical?
 
May also wish to add the `-p` option to scramble.  By default it modifies the PG headers to include the command line used for the file conversion.  That includes all command line options.

Also I would remove the `-t $task.cpus` bit.  When threaded, it's not guaranteed to be bit-identical every time as the order in which threads return could change some of the metrics.  Scramble has a learning algorithm for deciding which codecs to use based on sampling the first few blocks.  In threaded mode "first few blocks" may be different blocks.  Although it obviously outputs them in the correct order, the metrics used for deciding the codec parameters runs before writing out the sequential data.

**Comment by matthdsm** [comment]
Hi James,

Thanks for the answer. The path expansions are always the same. Adding `-q;Don't add scramble @PG header line` and settings threads to 1 didn't seem to help.

**Comment by jkbonfield** [comment]
I'm assuming removing the threading does however?

Fixing the threading to be consistent is quite a bit more work, and it's likely something I wouldn't bother with in Scramble.  Perhaps Htslib if people really care about it, as that's where the real "production" code lives these days.  (Scramble still serves a valid purpose though and it's often faster to release the more experimental features, but most of the speed advantages it previously had over Samtools have now been eroded, by us copying them over to Samtools :-).)

**Comment by matthdsm** [comment]
We just accepted the fact that the results aren't going to be bit identical and check for the existence of the file instead.
I assumed setting `-t 1` equals disabling threading, which didn't work. 
Thanks for the suggestions anyway!

**Comment by jkbonfield** [comment]
I think maybe -t 1 runs one additional worker thread (and main is dispatching / marshalling only), but I may be misremembering that.  No -t option is the way to completely disable threading.  I'm intrigued though as to how it can get variation when using 1 worker thread.

Anyway, it seems you're happy with this response so I'll close the issue.  Feel free to comment if you have further issues with this topic.

**Comment by matthdsm** [comment]
Thanks for all the help.
Just FYI, I ran the test with
```nextflow
    scramble \
        -q \
        -I bam \
        -O cram \
        -r ${fasta} \
        ${bam} \
        ${prefix}.cram
```
which did also not produce an identical result.

Matthias

**Comment by jkbonfield** [comment]
OK that is odd.  I've tried it on a few BAM files here and it's consistently identical.

Could you try saving the `cram_dump ${prefix}.cram` to a file for a couple runs?  Diffing that will give you some basic information on why it's differing.  I find this rather strange.  (Note you will see some differences with SM and TD preservation maps.  These are memory pointers and really shouldn't be dumped out that way!  It looks like I intended at some stage to expand the dump output there, but didn't complete it.  It's rather pointless at present to display a pointer.

Eg:

```
@ seq4c[samtools.../htscodecs]130; scramble -N 1000000 -r $HREF -q -I bam -O cram ~/scratch/data/novaseq.10m.bam 
06278e0423d79ef2681e3991242ee2fe  /tmp/_.cram
3bf5a5c6751618c9549c2c5780bd7122  -

@ seq4c[samtools.../htscodecs]; scramble -N 1000000 -r $HREF -q -I bam -O cram ~/scratch/data/novaseq.10m.bam /tmp/_.cram;md5sum /tmp/_.cram; cram_dump /tmp/_.cram | egrep -v '(SM|TD => ).*0x' |md5sum
06278e0423d79ef2681e3991242ee2fe  /tmp/_.cram
3bf5a5c6751618c9549c2c5780bd7122  -

# -t1 matches too
@ seq4c[samtools.../htscodecs]; scramble -t1 -N 1000000 -r $HREF -q -I bam -O cram ~/scratch/data/novaseq.10m.bam /tmp/_.cram;md5sum /tmp/_.cram; cram_dump /tmp/_.cram | egrep -v '(SM|TD => ).*0x' |md5sum
06278e0423d79ef2681e3991242ee2fe  /tmp/_.cram
3bf5a5c6751618c9549c2c5780bd7122  -

# But -t8 doesn't:
@ seq4c[samtools.../htscodecs]; scramble -t8 -N 1000000 -r $HREF -q -I bam -O cram ~/scratch/data/novaseq.10m.bam /tmp/_.cram;md5sum /tmp/_.cram; cram_dump /tmp/_.cram | egrep -v '(SM|TD => ).*0x' |md5sum
01822a62dea1f58eacf009d511a09a52  /tmp/_.cram
e21b9024fef659e8fdf4483003c086c3  -
```

**Comment by matthdsm** [comment]
Which package includes `cram_dump`? Is it part of io_lib?

**Comment by matthdsm** [comment]
nvm, found it.
Strangely enough, the checksums do match when I run it locally.
```
$ scramble -q -I bam -O cram -r genome.fasta test.paired_end.bam test.cram; md5sum test.cram;cram_dump test.cram | egrep -v '(SM|TD => ).*0x' |md5sum 
31dc5bc1ac7109aebf4adb281f81de42  test.cram
0e0815e80c128a8e5b12e0909141dc73  -
$ scramble -q -I bam -O cram -r genome.fasta test.paired_end.bam test.cram; md5sum test.cram;cram_dump test.cram | egrep -v '(SM|TD => ).*0x' |md5sum
31dc5bc1ac7109aebf4adb281f81de42  test.cram
0e0815e80c128a8e5b12e0909141dc73  -
$ scramble -q -I bam -O cram -r genome.fasta test.paired_end.bam test.cram; md5sum test.cram;cram_dump test.cram | egrep -v '(SM|TD => ).*0x' |md5sum
31dc5bc1ac7109aebf4adb281f81de42  test.cram
0e0815e80c128a8e5b12e0909141dc73  -
$ scramble -q -t 1 -I bam -O cram -r genome.fasta test.paired_end.bam test.cram; md5sum test.cram;cram_dump test.cram | egrep -v '(SM|TD => ).*0x' |md5sum
31dc5bc1ac7109aebf4adb281f81de42  test.cram
0e0815e80c128a8e5b12e0909141dc73  -
```

The difference must have something to do with the docker image or the test environment. I'll look into it further

**Comment by matthdsm** [comment]
Running in docker:
quay.io/biocontainers/staden_io_lib:1.14.14--h0d9da7e_3

cmd:
```
scramble -I bam -O cram -r genome.fasta -t 1 test.paired_end.bam test.cram
md5sum test.cram > checksum.txt
cram_dump test.cram | egrep -v '(SM|TD => ).*0x' |md5sum > cram_dump.txt
```
run 1
```
d6415468b3ebc590bd1d14f8978bb6e7  test.cram
622d8c8c4e616833be306d72f3e2f972  -
```
run 2
```
f21ebac2c26b44f9d2b26b42e93f2f4b  test.cram
cef1ed6272bd6420af934912699695b3  -
```

**Comment by matthdsm** [comment]
The input data does seem to check out:
```
d8037d0ae720c219d5d8cff45988483d  test.paired_end.bam
6e9fe4042a72f2345f644f239272b7e6  genome.fasta

6bef96d1d0e9384564abf20b0dcfa2f1  test.cram
84e85ed785d3d99607e0ed5dfe5061c4  -
```
```
d8037d0ae720c219d5d8cff45988483d  test.paired_end.bam
6e9fe4042a72f2345f644f239272b7e6  genome.fasta

11d8ddb81230f3fee4b364483c6a3b36  test.cram
37eaa9c30175997079486075782ba48d  -
```

**Comment by jkbonfield** [comment]
Can you save the cram_dump output (maybe post-grep) to files and diff them?  I don't see why Docker would change the behaviour, unless something about the image is making it into the file headers somewhere (even filename and directory can appear in the CRAM meta-data, although I'm not sure that was ever a sensible thing in the CRAM spec).

**Comment by matthdsm** [comment]
```
8c8
< @SQ   SN:MT192765.1   LN:29829        M5:c95f3e5592d0ad9974e41e7f0ea14eb0     UR:/tmp/pytest_workflow_35w06zcx/stadeniolib_test_stadeniolib/work/1a/6c5f47d818c258d30c1648ef62fca6/genome.fasta
---
> @SQ   SN:MT192765.1   LN:29829        M5:c95f3e5592d0ad9974e41e7f0ea14eb0     UR:/tmp/pytest_workflow_ta8ahpp3/stadeniolib_test_stadeniolib/work/73/3f52336dcb23a0ea8aacaebbe5dba4/genome.fasta
15c15
< Container pos 708 size 8869
---
> Container pos 705 size 8869
25c25
<     Container_header block pos 731
---
>     Container_header block pos 728
93c93
<     Slice 1/1, container offset 778, file offset 1509
---
>     Slice 1/1, container offset 778, file offset 1506
371c371
< Container pos 9600 size 15
---
> Container pos 9597 size 15
381c381
<     Container_header block pos 9623
---
>     Container_header block pos 9620
```

**Comment by matthdsm** [comment]
it does seems a path is in the @SQ header, some other differences too

**Comment by jkbonfield** [comment]
All the other differences just stem from the SAM header differing, which then changes compression sizes and offsets.

Having the filename in the UR field is a useful feature as, locally at least, it means the decoder doesn't need an explicit pointer to the reference being used (if it was supplied via a fasta argument rather than REF_PATH to a directory of md5sum files, which is the preferred more performant approach).

So I don't think there's much we can do about that.  It's good to know where the issue is though and to double check it's not something unexpected.  Thanks for helping to verify this.

**Comment by matthdsm** [comment]
You're very welcome, glad we could clear it up!

**Comment by jkbonfield** [comment]
I should add there is a request in samtools-land for the reference to be permitted as a relative path.  Eg along side the CRAM file, or ../dir/ref.fasta, etc.   This of course has pros and cons.  That would sort of solve this here too, but it's not something we've looked in to yet.

**Comment by matthdsm** [comment]
We'll be on the lookout for any evolutions
