### ISSUE TITLE
Issue when linking against htscodecs2 version 1.3.0

### ISSUE THREAD

**Issue by tillea** [jkbonfield/io_lib#50]
Hi,
as Bernhard Übelacker nicely [explained in a Debian bug report](https://bugs.debian.org/1022282#12) io_lib either needs a [patch](https://salsa.debian.org/med-team/staden-io-lib/-/blob/master/debian/patches/tok3_decode_names.patch) or probably better htscodecs2 should expose the said functions explicitly.
Kind regards, Andreas.

**Comment by jkbonfield** [comment]
I forgot about this, thanks.  Io_lib should definitely update to use the newer function names.

**Comment by jkbonfield** [comment]
In the commentary for the patch, it suggests the correct solution is adding these functions to the public header files for htscodecs.

At the time (IIRC) htscodecs was adopted as a formal part of Samtools et al, we also renamed these functions to not be so generic and make it more robust when htslib is used in conjunction with other packages (see https://github.com/samtools/htscodecs/issues/36).  That's quite a common scenario, and we've hit issues before with lack of sensible name-spacing of external symbols.  Removing them from the header file is essentially a warning that they're going, and likely in a future release will be culled permanently, while retaining ABI compatibility (but I didn't think that through).  Perhaps this would have been better handled with compiler-specific flags to mark them as deprecated, but given the transitory nature I hope for now we can just ignore the change there and deal with it properly whenever we next need to do an ABI-breaking change.

I'll incorporate the patch, along with an additional update.  Many thanks.

**Comment by jkbonfield** [comment]
Fixed in https://github.com/jkbonfield/io_lib/commit/9f30677f994fea700e08de01ba129a58cd239d4b
