### ISSUE TITLE
Bug in aux field parsing

### ISSUE THREAD

**Issue by rob-p** [jkbonfield/io_lib#51]
Hi @jkbonfield,

  My student @zzare-umd was working on some code that parses BAM tags to propagate information about alignments and ran into a strange bug.  In the attached file, each of the alignments has a float field named `pb`; these are probabilities (and so all between 0 and 1, inclusive).  If one uses `samtools view` to look at the records, they observe this fact.

  Yet, when we parse these records with `io_lib`, we get wildly different values for the tags.  The zeros remain a zero, but the other floating point numbers become very large values.  Below, we have minimal code to loop through and print out these values so that you can see the output.

  ~Digging into the code a bit and comparing it to what `htslib` does, I *believe* the problem is that the tags are all written in the (common) native machine format (little endian).  When `htslib` parses the file, there is a compile time `#ifdef` so that, if the reading machine is little endian, the values are taken as is and cast to the right type, and if the reading machine is big endian, the bytes are swapped.  However, in `io_lib`, the bytes are *always* swapped, regardless of the machine being used to read the file.  This means that if I write and read the file on the same (little endian) machine, the tags are trashed when they are read because the the bytes are all swapped (i.e. I don't get out what I put in).~

  I think the problem is related to the way in which the raw bytes are first cast to an int32_t and then cast (via a C-style cast, which corresponds roughly to a modern C++-style `static_cast<>`) into a `float`.  This is not the desired behavior.  Rather, we simply want to _interpret_ the sequences of constructed bits as a `float`. The proper way to do this (as it seems is currently done in htslib as well) is to launder the bytes through a `union` with a float element.

  Here is a MWE piece of parsing code, and a small file that exhibits the behavior is included below. Once compiled, the program takes a single argument which is the input BAM file.

```
//obtaining the pb values of the BAM file and print out
#include <iostream>
extern "C"
{
#include "io_lib/bam.h"
}

int main(int argc, char *argv[])
{
    bam_file_t *fpr = bam_open(argv[1], "rb");
    bam_seq_t *b = reinterpret_cast<bam_seq_t*>(calloc(1, sizeof(bam_seq_t)));

    while (bam_get_seq(fpr, &b) > 0) {
      uint8_t* tl = reinterpret_cast<uint8_t*>(bam_aux_find(b, "pb"));
      float score = bam_aux_f(tl);
      std::cout << "score is: " << score << "\n";
    }
  bam_close(fpr);
  return 0;
}
```

  Since we rely *heavily* on `io_lib` in `salmon`, we are very eager to have this fixed. Let us know how we can help!

Thanks!
Rob

[test.bam.zip](https://github.com/jkbonfield/io_lib/files/10142071/test.bam.zip)

**Note** : GitHub would't let me upload something with the `.bam` suffix, so `test.bam.zip` is just the regular bam file.

**Comment by rob-p** [comment]
Looking more closely at the issue — it may, perhaps, not be due to the endian-ness, but the way in which the casts are done to convert the binary representation into a float.  I think the current `bam_aux_f()` function simply *casts* the `int32_t` representation as a `float`, which does not re-interpret the underlying bits in that way, but rather represents the `int32_t` as a `float` (i.e. the value stays approximately the same and the bit pattern changes). 

For example, the following code does the "right thing" (in a dirty hack way):

```
//obtaining the pb values of the BAM file and print out
#include <iostream>
extern "C" {
  #include "io_lib/bam.h"
}

float int32_to_float(int32_t i){
    union
    {
        float f;
        int32_t i;
        char b[4];
    } src, dst;

    src.i = i;
    dst.f = src.f;
    return dst.f;
}

inline float get_float_tag(uint8_t* tag_info) {
  // We have to do this song-and-dance to get
  // a proper float field out due to a bug (https://github.com/jkbonfield/io_lib/issues/51).
  // Until we have a fix for that, we can do the following to get out a proper float value.

  // to not mess with the actual value, interpret the
  // bytes of the float as an int.
  tag_info[0] = 'i';
  return int32_to_float(bam_aux_i(tag_info));
}

int main(int argc, char *argv[]) {
    bam_file_t *fpr = bam_open(argv[1], "rb");
    bam_seq_t *b = reinterpret_cast<bam_seq_t*>(calloc(1, sizeof(bam_seq_t)));

    while (bam_get_seq(fpr, &b) > 0) {
      uint8_t* tl = reinterpret_cast<uint8_t*>(bam_aux_find(b, "pb"));
      float score = get_float_tag(tl);
      std::cout << "score is: " << score << "\n";
    }
  bam_close(fpr);
  return 0;
}
```

**Comment by jkbonfield** [comment]
You're correct.

The on-disk format for BAM is basically the raw IEEE float stored as-is (presumably in endian-aware ordering).  The cast is the incorrect way to do this.

I'll fix it.

**Comment by jkbonfield** [comment]
Thanks for reporting this.   It's now been fixed in master.

The last release was in March 2021 so I may consider making an official release to bundle up a few other changes too.

**Comment by rob-p** [comment]
Thanks for the quick response and fix @jkbonfield! If you could get around to tagging another official release, that would be great. We prefer to rely on tagged releases than specific commit hashes.
